// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Index_for_VehicleId_OnVSum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Index_for_VehicleId_OnVSum));
        
        string IMigrationMetadata.Id
        {
            get { return "201903260958536_Index_for_VehicleId_OnVSum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
