//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Scania.Baseline {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class vehicles {
        
        private vehiclesVehicle[] vehicleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle", Order=0)]
        public vehiclesVehicle[] vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicle {
        
        private string manufacturerField;
        
        private string manufacturerAddressField;
        
        private string vINField;
        
        private string modelField;
        
        private System.DateTime dateField;
        
        private byte developmentLevelField;
        
        private string legislativeClassField;
        
        private string vehicleCategoryField;
        
        private string axleConfigurationField;
        
        private string curbMassChassisField;
        
        private string grossVehicleMassField;
        
        private string idlingSpeedField;
        
        private string retarderTypeField;
        
        private string retarderRatioField;
        
        private string angledriveTypeField;
        
        private vehiclesVehiclePTO pTOField;
        
        private vehiclesVehicleComponents componentsField;
        
        public vehiclesVehicle() {
            this.manufacturerField = "Scania";
            this.manufacturerAddressField = "Soedertaelje";
            this.retarderTypeField = "None";
            this.retarderRatioField = "0";
            this.angledriveTypeField = "None";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("Scania")]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("Soedertaelje")]
        public string ManufacturerAddress {
            get {
                return this.manufacturerAddressField;
            }
            set {
                this.manufacturerAddressField = value;
            }
        }
        
        /// <remarks/>
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public byte DevelopmentLevel {
            get {
                return this.developmentLevelField;
            }
            set {
                this.developmentLevelField = value;
            }
        }
        
        /// <remarks/>
        public string LegislativeClass {
            get {
                return this.legislativeClassField;
            }
            set {
                this.legislativeClassField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleCategory {
            get {
                return this.vehicleCategoryField;
            }
            set {
                this.vehicleCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string AxleConfiguration {
            get {
                return this.axleConfigurationField;
            }
            set {
                this.axleConfigurationField = value;
            }
        }
        
        /// <remarks/>
        public string CurbMassChassis {
            get {
                return this.curbMassChassisField;
            }
            set {
                this.curbMassChassisField = value;
            }
        }
        
        /// <remarks/>
        public string GrossVehicleMass {
            get {
                return this.grossVehicleMassField;
            }
            set {
                this.grossVehicleMassField = value;
            }
        }
        
        /// <remarks/>
        public string IdlingSpeed {
            get {
                return this.idlingSpeedField;
            }
            set {
                this.idlingSpeedField = value;
            }
        }
        
        /// <remarks/>
        public string RetarderType {
            get {
                return this.retarderTypeField;
            }
            set {
                this.retarderTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RetarderRatio {
            get {
                return this.retarderRatioField;
            }
            set {
                this.retarderRatioField = value;
            }
        }
        
        /// <remarks/>
        public string AngledriveType {
            get {
                return this.angledriveTypeField;
            }
            set {
                this.angledriveTypeField = value;
            }
        }
        
        /// <remarks/>
        public vehiclesVehiclePTO PTO {
            get {
                return this.pTOField;
            }
            set {
                this.pTOField = value;
            }
        }
        
        /// <remarks/>
        public vehiclesVehicleComponents Components {
            get {
                return this.componentsField;
            }
            set {
                this.componentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehiclePTO {
        
        private string pTOShaftsGearWheelsField;
        
        private string pTOOtherElementsField;
        
        public vehiclesVehiclePTO() {
            this.pTOShaftsGearWheelsField = "none";
            this.pTOOtherElementsField = "none";
        }
        
        /// <remarks/>
        public string PTOShaftsGearWheels {
            get {
                return this.pTOShaftsGearWheelsField;
            }
            set {
                this.pTOShaftsGearWheelsField = value;
            }
        }
        
        /// <remarks/>
        public string PTOOtherElements {
            get {
                return this.pTOOtherElementsField;
            }
            set {
                this.pTOOtherElementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponents {
        
        private vehiclesVehicleComponentsEngine engineField;
        
        private string gearBoxPDField;
        
        private string axleGearPDField;
        
        private string retarderPDField;
        
        private string torqueConverterPDField;
        
        private vehiclesVehicleComponentsAirDrag airDragField;
        
        private vehiclesVehicleComponentsAuxiliaries auxiliariesField;
        
        private vehiclesVehicleComponentsAxleWheels axleWheelsField;
        
        /// <remarks/>
        public vehiclesVehicleComponentsEngine Engine {
            get {
                return this.engineField;
            }
            set {
                this.engineField = value;
            }
        }
        
        /// <remarks/>
        public string GearBoxPD {
            get {
                return this.gearBoxPDField;
            }
            set {
                this.gearBoxPDField = value;
            }
        }
        
        /// <remarks/>
        public string AxleGearPD {
            get {
                return this.axleGearPDField;
            }
            set {
                this.axleGearPDField = value;
            }
        }
        
        /// <remarks/>
        public string RetarderPD {
            get {
                return this.retarderPDField;
            }
            set {
                this.retarderPDField = value;
            }
        }
        
        /// <remarks/>
        public string TorqueConverterPD {
            get {
                return this.torqueConverterPDField;
            }
            set {
                this.torqueConverterPDField = value;
            }
        }
        
        /// <remarks/>
        public vehiclesVehicleComponentsAirDrag AirDrag {
            get {
                return this.airDragField;
            }
            set {
                this.airDragField = value;
            }
        }
        
        /// <remarks/>
        public vehiclesVehicleComponentsAuxiliaries Auxiliaries {
            get {
                return this.auxiliariesField;
            }
            set {
                this.auxiliariesField = value;
            }
        }
        
        /// <remarks/>
        public vehiclesVehicleComponentsAxleWheels AxleWheels {
            get {
                return this.axleWheelsField;
            }
            set {
                this.axleWheelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsEngine {
        
        private string enginePDField;
        
        private string engineStrokeVolumeField;
        
        public vehiclesVehicleComponentsEngine() {
            this.enginePDField = "none";
            this.engineStrokeVolumeField = "none";
        }
        
        /// <remarks/>
        public string EnginePD {
            get {
                return this.enginePDField;
            }
            set {
                this.enginePDField = value;
            }
        }
        
        /// <remarks/>
        public string EngineStrokeVolume {
            get {
                return this.engineStrokeVolumeField;
            }
            set {
                this.engineStrokeVolumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsAirDrag {
        
        private string airDragPDField;
        
        private string airDragModelField;
        
        public vehiclesVehicleComponentsAirDrag() {
            this.airDragPDField = "none";
            this.airDragModelField = "none";
        }
        
        /// <remarks/>
        public string AirDragPD {
            get {
                return this.airDragPDField;
            }
            set {
                this.airDragPDField = value;
            }
        }
        
        /// <remarks/>
        public string AirDragModel {
            get {
                return this.airDragModelField;
            }
            set {
                this.airDragModelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsAuxiliaries {
        
        private vehiclesVehicleComponentsAuxiliariesData dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public vehiclesVehicleComponentsAuxiliariesData Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsAuxiliariesData {
        
        private vehiclesVehicleComponentsAuxiliariesDataFan fanField;
        
        private vehiclesVehicleComponentsAuxiliariesDataSteeringPump steeringPumpField;
        
        private vehiclesVehicleComponentsAuxiliariesDataElectricSystem electricSystemField;
        
        private vehiclesVehicleComponentsAuxiliariesDataPneumaticSystem pneumaticSystemField;
        
        private vehiclesVehicleComponentsAuxiliariesDataHVAC hVACField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public vehiclesVehicleComponentsAuxiliariesDataFan Fan {
            get {
                return this.fanField;
            }
            set {
                this.fanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public vehiclesVehicleComponentsAuxiliariesDataSteeringPump SteeringPump {
            get {
                return this.steeringPumpField;
            }
            set {
                this.steeringPumpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public vehiclesVehicleComponentsAuxiliariesDataElectricSystem ElectricSystem {
            get {
                return this.electricSystemField;
            }
            set {
                this.electricSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public vehiclesVehicleComponentsAuxiliariesDataPneumaticSystem PneumaticSystem {
            get {
                return this.pneumaticSystemField;
            }
            set {
                this.pneumaticSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public vehiclesVehicleComponentsAuxiliariesDataHVAC HVAC {
            get {
                return this.hVACField;
            }
            set {
                this.hVACField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsAuxiliariesDataFan {
        
        private string technologyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Technology {
            get {
                return this.technologyField;
            }
            set {
                this.technologyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsAuxiliariesDataSteeringPump {
        
        private string technologyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Technology {
            get {
                return this.technologyField;
            }
            set {
                this.technologyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsAuxiliariesDataElectricSystem {
        
        private string technologyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Technology {
            get {
                return this.technologyField;
            }
            set {
                this.technologyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsAuxiliariesDataPneumaticSystem {
        
        private string technologyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Technology {
            get {
                return this.technologyField;
            }
            set {
                this.technologyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsAuxiliariesDataHVAC {
        
        private string technologyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Technology {
            get {
                return this.technologyField;
            }
            set {
                this.technologyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsAxleWheels {
        
        private vehiclesVehicleComponentsAxleWheelsData dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public vehiclesVehicleComponentsAxleWheelsData Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsAxleWheelsData {
        
        private vehiclesVehicleComponentsAxleWheelsDataAxle[] axlesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Axle", IsNullable=false)]
        public vehiclesVehicleComponentsAxleWheelsDataAxle[] Axles {
            get {
                return this.axlesField;
            }
            set {
                this.axlesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicleComponentsAxleWheelsDataAxle {
        
        private string axleTypeField;
        
        private bool twinTyresField;
        
        private bool steeredField;
        
        private string tyrePDField;
        
        private uint axleNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AxleType {
            get {
                return this.axleTypeField;
            }
            set {
                this.axleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool TwinTyres {
            get {
                return this.twinTyresField;
            }
            set {
                this.twinTyresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Steered {
            get {
                return this.steeredField;
            }
            set {
                this.steeredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TyrePD {
            get {
                return this.tyrePDField;
            }
            set {
                this.tyrePDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint axleNumber {
            get {
                return this.axleNumberField;
            }
            set {
                this.axleNumberField = value;
            }
        }
    }
}
