//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Scania.Baseline.SchemaB {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class vehicles {
        
        private vehiclesVehicle[] vehicleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle")]
        public vehiclesVehicle[] vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vehiclesVehicle {
		public static implicit operator vehiclesVehicle(Scania.Baseline.vehiclesVehicle vehicle)
		{
			var convertedVehicle = new vehiclesVehicle();
			convertedVehicle.Manufacturer = vehicle.Manufacturer;
			convertedVehicle.ManufacturerAddress = vehicle.ManufacturerAddress;
			convertedVehicle.Model = vehicle.Model;
			convertedVehicle.VIN = vehicle.VIN;
			convertedVehicle.Date = vehicle.Date;
			convertedVehicle.LegislativeClass = vehicle.LegislativeClass;
			convertedVehicle.VehicleCategory = vehicle.VehicleCategory;
			convertedVehicle.CurbMassChassis = vehicle.CurbMassChassis;
			convertedVehicle.GrossVehicleMass = vehicle.GrossVehicleMass;
			convertedVehicle.ZeroEmissionVehicle = vehicle.ZeroEmissionVehicle;
			convertedVehicle.MaxNetPower1 = vehicle.MaxNetPower1;
			convertedVehicle.MaxNetPower2 = vehicle.MaxNetPower2;
			convertedVehicle.HybridElectricHDV = vehicle.HybridElectricHDV;
			convertedVehicle.DualFuelVehicle = vehicle.DualFuelVehicle;

			return convertedVehicle;
			//return new Scania.Baseline.SchemaA.vehicles
			//{
			//	//vehicle = vehicles.vehicle

			//};
		}

		private string manufacturerField;
        
        private string manufacturerAddressField;
        
        private string modelField;
        
        private string vINField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string legislativeClassField;
        
        private string vehicleCategoryField;
        
        private string curbMassChassisField;
        
        private string grossVehicleMassField;
        
        private bool zeroEmissionVehicleField;
        
        private bool zeroEmissionVehicleFieldSpecified;
        
        private string maxNetPower1Field;
        
        private string maxNetPower2Field;
        
        private bool hybridElectricHDVField;
        
        private bool hybridElectricHDVFieldSpecified;
        
        private bool dualFuelVehicleField;
        
        private bool dualFuelVehicleFieldSpecified;
        
        private string idField;
        
        /// <remarks/>
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        public string ManufacturerAddress {
            get {
                return this.manufacturerAddressField;
            }
            set {
                this.manufacturerAddressField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string LegislativeClass {
            get {
                return this.legislativeClassField;
            }
            set {
                this.legislativeClassField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleCategory {
            get {
                return this.vehicleCategoryField;
            }
            set {
                this.vehicleCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string CurbMassChassis {
            get {
                return this.curbMassChassisField;
            }
            set {
                this.curbMassChassisField = value;
            }
        }
        
        /// <remarks/>
        public string GrossVehicleMass {
            get {
                return this.grossVehicleMassField;
            }
            set {
                this.grossVehicleMassField = value;
            }
        }
        
        /// <remarks/>
        public bool ZeroEmissionVehicle {
            get {
                return this.zeroEmissionVehicleField;
            }
            set {
                this.zeroEmissionVehicleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZeroEmissionVehicleSpecified {
            get {
                return this.zeroEmissionVehicleFieldSpecified;
            }
            set {
                this.zeroEmissionVehicleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MaxNetPower1 {
            get {
                return this.maxNetPower1Field;
            }
            set {
                this.maxNetPower1Field = value;
            }
        }
        
        /// <remarks/>
        public string MaxNetPower2 {
            get {
                return this.maxNetPower2Field;
            }
            set {
                this.maxNetPower2Field = value;
            }
        }
        
        /// <remarks/>
        public bool HybridElectricHDV {
            get {
                return this.hybridElectricHDVField;
            }
            set {
                this.hybridElectricHDVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HybridElectricHDVSpecified {
            get {
                return this.hybridElectricHDVFieldSpecified;
            }
            set {
                this.hybridElectricHDVFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool DualFuelVehicle {
            get {
                return this.dualFuelVehicleField;
            }
            set {
                this.dualFuelVehicleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DualFuelVehicleSpecified {
            get {
                return this.dualFuelVehicleFieldSpecified;
            }
            set {
                this.dualFuelVehicleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}
